server:
  port: 9008

spring:
  application:
    name: zipkin-server
  datasource:
    url: jdbc:mysql://localhost:3306/spring-cloud-zipkin?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 1993
    driver-class-name: com.mysql.jdbc.Driver

zipkin:
  storage:
    type: mysql

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false
