server:
  port: 9007

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wuychn/SpringCloudConfig
          searchPaths: respo
          username: wuychn
          password:
      label: master
  application:
    name: config-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/