server:
  port: 9011
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:9009
management:
  endpoints:
    web:
      exposure:
        include: "*"