server:
  port: 9004

spring:
  application:
    name: service-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
      health:
        show-details: ALWAYS